name: Continuous Integration

on: [push, pull_request]

jobs:
  tpm-provider:
    name: Integration tests using TPM provider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run the container to execute the test script
        run: docker run -v $(pwd):/tmp/parsec-se-driver -w /tmp/parsec-se-driver ghcr.io/parallaxsecond/parsec-service-test-all /tmp/parsec-se-driver/ci/ci.sh
